package QRCode.scanManage;

import QRCode.base.DataBaseUtil;
import QRCode.base.StringUtils;
import QRCode.compnents.MessageUtils;
import QRCode.product.model.Stock;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.KeyStroke;
import javax.swing.JComponent;

/**
 *
 * @author jiangchunyang
 */
public class PalBarcodeScan extends javax.swing.JPanel {

    private int id = 0;

    /** Creates new form PalBarcodeScan */
    public PalBarcodeScan() {
        initComponents();
        btnSave.registerKeyboardAction(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                saveOrUpdate(getModel());
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, InputEvent.CTRL_DOWN_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtProdCode = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        remark = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        txtProdNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRemainShare = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("快速入库"));

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel5.setText("进价：");
        jLabel5.setName("jLabel5"); // NOI18N

        txtProdCode.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtProdCode.setName("txtProdCode"); // NOI18N
        txtProdCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdCodeActionPerformed(evt);
            }
        });
        txtProdCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdCodeKeyReleased(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        remark.setColumns(20);
        remark.setFont(new java.awt.Font("Monospaced", 0, 18));
        remark.setRows(5);
        remark.setBorder(javax.swing.BorderFactory.createTitledBorder("备注"));
        remark.setName("remark"); // NOI18N
        jScrollPane2.setViewportView(remark);

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel4.setText("产品别名：");
        jLabel4.setName("jLabel4"); // NOI18N

        txtName2.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtName2.setName("txtName2"); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel1.setText("产品名称：");
        jLabel1.setName("jLabel1"); // NOI18N

        txtInPrice.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtInPrice.setName("txtInPrice"); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel2.setText("条码号：");
        jLabel2.setName("jLabel2"); // NOI18N

        txtProdName.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtProdName.setName("txtProdName"); // NOI18N

        txtProdNum.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtProdNum.setName("txtProdNum"); // NOI18N

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel7.setText("入库件数：");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel8.setText("库存：");
        jLabel8.setName("jLabel8"); // NOI18N

        txtRemainShare.setEditable(false);
        txtRemainShare.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtRemainShare.setName("txtRemainShare"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName2)
                            .addComponent(txtProdName)
                            .addComponent(txtProdCode, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProdNum))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRemainShare)
                                    .addComponent(txtInPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProdCode, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtProdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtInPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtRemainShare, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        btnSave.setText("保存");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int saveOrUpdate(Stock stock) {
        int i = 0;
        if (stock.getId() != null) {
            long number = Long.valueOf(txtProdNum.getText());
            stock.setRemainshare(stock.getRemainshare() + number);
            i = DataBaseUtil.updateStock(stock);
        } else {
            stock.setRemainshare(1l);
            i = DataBaseUtil.saveStock(stock);
        }
       reQueryPage();
        return i;
    }

    private Stock getModel() {
        Stock stock = new Stock();
        if (id != 0) {
            stock.setId(id);
        }
        stock.setBarcode(txtProdCode.getText());
        stock.setName2(txtName2.getText());
        stock.setName(txtProdName.getText());
        stock.setInPrice(new BigDecimal(txtInPrice.getText()));
        stock.setRemainshare(Long.valueOf(txtRemainShare.getText()));
        stock.setRemark(remark.getText());
        return stock;
    }
private void txtProdCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdCodeActionPerformed
}//GEN-LAST:event_txtProdCodeActionPerformed

private void txtProdCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdCodeKeyReleased
    if (10 == evt.getKeyCode()) {
        String barCode = txtProdCode.getText();
        setModel(barCode);
    }
}//GEN-LAST:event_txtProdCodeKeyReleased

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    if(StringUtils.isNullOrEmpty(txtProdNum.getText())){
        return;
    }
    saveOrUpdate(getModel());
}//GEN-LAST:event_btnSaveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea remark;
    private javax.swing.JTextField txtInPrice;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtProdCode;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdNum;
    private javax.swing.JTextField txtRemainShare;
    // End of variables declaration//GEN-END:variables

    private void setModel(String barCode) {
        Stock stock = DataBaseUtil.findStockByBarCode(barCode);
        if (stock != null) {
            txtProdName.setText(stock.getName());
            txtName2.setText(stock.getName2());
            txtProdCode.setText(stock.getBarcode());
            remark.setText(stock.getRemark());
            txtProdNum.setText("1");
            txtInPrice.setText(stock.getInPrice().toString());
            txtRemainShare.setText(stock.getRemainshare().toString());
            id = stock.getId();
        } else {
            id = 0;
            resetPage();
            MessageUtils.showErrorMessage("未找到该商品信息，请快速录入商品或在新增功能中录入商品！", this);
        }
    }

    void resetPage() {
        txtProdName.setText(null);
        txtName2.setText(null);
        remark.setText(null);
        txtProdNum.setText(null);
        txtInPrice.setText(null);
        txtRemainShare.setText(null);
    }

    private void reQueryPage() {
           Stock stock = DataBaseUtil.findStockByBarCode(txtProdCode.getText());
        if (stock != null) {
            txtProdName.setText(stock.getName());
            txtName2.setText(stock.getName2());
            txtProdCode.setText(stock.getBarcode());
            remark.setText(stock.getRemark());
            txtProdNum.setText("1");
            txtInPrice.setText(stock.getInPrice().toString());
            txtRemainShare.setText(stock.getRemainshare().toString());
            id = stock.getId();
        }
    }
}
