/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalProductDetail.java
 *
 * Created on 2017-10-7, 14:24:37
 */
package QRCode.product;

import QRCode.base.Constants;
import QRCode.base.DataBaseUtil;
import QRCode.base.DateUtils;
import QRCode.compnents.BaseDetailPanel;
import QRCode.compnents.MessageUtils;
import QRCode.product.model.Prod;
import com.mysql.jdbc.StringUtils;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class PalProductDetail extends BaseDetailPanel {

    /** Creates new form PalProductDetail */
    public PalProductDetail(String operationType) {
        initComponents();
        initData();
        setOperationType(operationType);
    }

    /** Creates new form PalProductDetail */
    public PalProductDetail(String operationType, Integer id) {
        initComponents();
        this.id = id;
        setOperationType(operationType);
        initData();
    }

    /** Creates new form PalProductDetail */
    public PalProductDetail(JFrame pfa, JPanel parentJpanel, String operationType) {
        initComponents();
        setParentJframe(pfa);
        setParentJpanel(parentJpanel);
        setOperationType(operationType);
        initData();
    }

    private void initData() {
        toxicity.setModelWithParam(DataBaseUtil.queryParamByPid("TOXICITY"));
        txtpesticideType.setModelWithParam(DataBaseUtil.queryParamByPid("PESTICIDE"));
        liquidType.setModelWithParam(DataBaseUtil.queryParamByPid("LIQUID"));
        useMethod.setModelWithParam(DataBaseUtil.queryParamByPid("USE_METHOD"));
       // txtCompany.setModel(DataBaseUtil.queryCompanyForCombo());
        comboPeriod.setModelWithParam(DataBaseUtil.queryParamByPid("PERIOD"));
        startDate.setSelectDate(new Date());
        endDate.setSelectDate(new Date());
        if (Constants.OPER_EDIT.equals(operationType)) {
            setModel(id);
            txtProdCode.setEnabled(false);
            registerCode.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilCalendarModel1 = new net.sourceforge.jdatepicker.impl.UtilCalendarModel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        txtProdCode = new javax.swing.JTextField();
        percent = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        registerCode = new javax.swing.JTextField();
        registerName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remark = new javax.swing.JTextArea();
        startDate = new QRCode.compnents.MyDatePicker();
        endDate = new QRCode.compnents.MyDatePicker();
        dosageMessage = new javax.swing.JTextField();
        applicableObject = new javax.swing.JTextField();
        protectObject = new javax.swing.JTextField();
        toxicity = new QRCode.compnents.MyCombobox();
        txtpesticideType = new QRCode.compnents.MyCombobox();
        liquidType = new QRCode.compnents.MyCombobox();
        useMethod = new QRCode.compnents.MyCombobox();
        jLabel15 = new javax.swing.JLabel();
        txtProdApproveCode = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUseFor = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboPeriod = new QRCode.compnents.MyCombobox();
        txtCompany = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel1.setText("产品名称：");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel2.setText("产品标准号：");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel3.setText("有效起始日期：");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel4.setText("登记证号：");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel5.setText("登记名称：");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel6.setText("农药类别：");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel7.setText("毒性：");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel8.setText("剂型：");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel9.setText("总含量(%)：");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel10.setText("有效结束日期：");
        jLabel10.setName("jLabel10"); // NOI18N

        txtProdName.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtProdName.setName("txtProdName"); // NOI18N

        txtProdCode.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtProdCode.setName("txtProdCode"); // NOI18N

        percent.setFont(new java.awt.Font("微软雅黑", 0, 14));
        percent.setName("percent"); // NOI18N

        jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel11.setText("适用对象：");
        jLabel11.setName("jLabel11"); // NOI18N

        registerCode.setFont(new java.awt.Font("微软雅黑", 0, 14));
        registerCode.setName("registerCode"); // NOI18N

        registerName.setFont(new java.awt.Font("微软雅黑", 0, 14));
        registerName.setName("registerName"); // NOI18N

        jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel12.setText("防治对象：");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel13.setText("有效成分用料量：");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel14.setText("使用方法：");
        jLabel14.setName("jLabel14"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        remark.setColumns(20);
        remark.setFont(new java.awt.Font("Monospaced", 0, 18));
        remark.setRows(5);
        remark.setBorder(javax.swing.BorderFactory.createTitledBorder("备注"));
        remark.setName("remark"); // NOI18N
        jScrollPane1.setViewportView(remark);

        startDate.setName("startDate"); // NOI18N

        endDate.setName("endDate"); // NOI18N

        dosageMessage.setFont(new java.awt.Font("微软雅黑", 0, 14));
        dosageMessage.setName("dosageMessage"); // NOI18N

        applicableObject.setFont(new java.awt.Font("微软雅黑", 0, 14));
        applicableObject.setName("applicableObject"); // NOI18N

        protectObject.setFont(new java.awt.Font("微软雅黑", 0, 14));
        protectObject.setName("protectObject"); // NOI18N

        toxicity.setName("toxicity"); // NOI18N

        txtpesticideType.setName("txtpesticideType"); // NOI18N

        liquidType.setName("liquidType"); // NOI18N

        useMethod.setName("useMethod"); // NOI18N

        jLabel15.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel15.setText("农药生产批准号：");
        jLabel15.setName("jLabel15"); // NOI18N

        txtProdApproveCode.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtProdApproveCode.setName("txtProdApproveCode"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtUseFor.setColumns(20);
        txtUseFor.setFont(new java.awt.Font("Monospaced", 0, 18));
        txtUseFor.setRows(5);
        txtUseFor.setBorder(javax.swing.BorderFactory.createTitledBorder("产品用途"));
        txtUseFor.setName("txtUseFor"); // NOI18N
        jScrollPane2.setViewportView(txtUseFor);

        jLabel16.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel16.setText("生产公司：");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel17.setText("有效日期(年)：");
        jLabel17.setName("jLabel17"); // NOI18N

        comboPeriod.setName("comboPeriod"); // NOI18N

        txtCompany.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtCompany.setName("txtCompany"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(percent)
                            .addComponent(txtProdCode)
                            .addComponent(txtProdName)
                            .addComponent(txtProdApproveCode, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(dosageMessage)
                            .addComponent(comboPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpesticideType, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toxicity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(liquidType, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213))
                            .addComponent(useMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(protectObject, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(applicableObject, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(registerName, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(registerCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(startDate, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addGap(213, 213, 213))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboPeriod, liquidType, toxicity, txtpesticideType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {endDate, startDate, useMethod});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtProdCode, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(registerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(registerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtProdApproveCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCompany, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(comboPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtpesticideType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(toxicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(applicableObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(liquidType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dosageMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(protectObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {applicableObject, dosageMessage, endDate, jLabel2, percent, protectObject, registerCode, registerName, startDate, txtProdApproveCode, txtProdCode, txtProdName, useMethod});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboPeriod, liquidType, toxicity, txtpesticideType});

        btnSave.setText("保存");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnSave});

    }// </editor-fold>//GEN-END:initComponents

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    Prod prod = getModel();
    int i = 0;
    if (Constants.OPER_ADD.equals(operationType)) {
        i = DataBaseUtil.saveProd(prod);
    } else {
        i = DataBaseUtil.updateProd(prod);
    }

    if (i > 0) {
        JOptionPane.showMessageDialog(this, "保存成功！");
        parentJframe.dispose();
       
    } else {
        JOptionPane.showMessageDialog(this, "保存失败！");
    }
}//GEN-LAST:event_btnSaveActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    parentJframe.dispose();
}//GEN-LAST:event_btnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField applicableObject;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private QRCode.compnents.MyCombobox comboPeriod;
    private javax.swing.JTextField dosageMessage;
    private QRCode.compnents.MyDatePicker endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private QRCode.compnents.MyCombobox liquidType;
    private javax.swing.JTextField percent;
    private javax.swing.JTextField protectObject;
    private javax.swing.JTextField registerCode;
    private javax.swing.JTextField registerName;
    private javax.swing.JTextArea remark;
    private QRCode.compnents.MyDatePicker startDate;
    private QRCode.compnents.MyCombobox toxicity;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtProdApproveCode;
    private javax.swing.JTextField txtProdCode;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextArea txtUseFor;
    private QRCode.compnents.MyCombobox txtpesticideType;
    private QRCode.compnents.MyCombobox useMethod;
    private net.sourceforge.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    // End of variables declaration//GEN-END:variables

    private Prod getModel() {
        Prod prod = new Prod();
        if (id != null) {
            prod.setId(id);
        } else {
            prod.setCreatetime(new Date());
        }
        prod.setProdname(txtProdName.getText());
        prod.setProdcode(txtProdCode.getText());
        prod.setRegistercode(registerCode.getText());
        prod.setRegistername(registerName.getText());
        if (!StringUtils.isNullOrEmpty(txtpesticideType.getSelectValue())) {
            prod.setPesticidetype(new Integer(txtpesticideType.getSelectValue()));
        }else{
            MessageUtils.showErrorMessage(jLabel6.getText()+ "必须输入", this);
        }
        if (!StringUtils.isNullOrEmpty(toxicity.getSelectValue())) {
            prod.setToxicity(new Integer(toxicity.getSelectValue()));
        }else{
          MessageUtils.showErrorMessage(jLabel7.getText()+ "必须输入", this);
        }
        prod.setStartdate(DateUtils.str2Date((String) startDate.getSelectedItem()));
        prod.setEnddate(DateUtils.str2Date((String) endDate.getSelectedItem()));
        if (!StringUtils.isNullOrEmpty(liquidType.getSelectValue())) {
            prod.setLiquidtype(new Integer(liquidType.getSelectValue()));
        }
        if (!StringUtils.isNullOrEmpty(percent.getText())) {
            prod.setPercent(new Float(percent.getText()));
        }
        prod.setDosagemessage(dosageMessage.getText());
        prod.setApplicableobject(applicableObject.getText());
        prod.setProtectobject(protectObject.getText());
        if (!StringUtils.isNullOrEmpty(useMethod.getSelectValue())) {
            prod.setUsemethod(new Integer(useMethod.getSelectValue()));
        }
        prod.setRemark(remark.getText());
          if (!StringUtils.isNullOrEmpty(comboPeriod.getSelectValue())) {
            prod.setToxicity(new Integer(comboPeriod.getSelectValue()));
        }else{
          MessageUtils.showErrorMessage(jLabel17.getText()+ "必须输入", this);
        }
        if (!StringUtils.isNullOrEmpty(txtCompany.getText())) {
            prod.setCompany(txtCompany.getText());
        }else{
          MessageUtils.showErrorMessage(jLabel17.getText()+ "必须输入", this);
        }
          
        return prod;
    }

    public void setModel(Integer id) {
        this.id = id;
        Prod prod = DataBaseUtil.findProdByid(id);
        txtProdName.setText(prod.getProdname());
        txtProdCode.setText(prod.getProdcode());
        registerCode.setText(prod.getRegistercode());
        registerName.setText(prod.getRegistername());
        txtCompany.setText(prod.getCompany());
        if (prod.getPesticidetype() != null) {
            txtpesticideType.setSelectValue(prod.getPesticidetype().toString());
        }
        if (prod.getToxicity() != null) {
            toxicity.setSelectValue(prod.getToxicity().toString());
        }
        if (prod.getStartdate() != null) {
            startDate.setText(DateUtils.date2Str(prod.getStartdate()));
        }
        if (prod.getEnddate() != null) {
            endDate.setText(DateUtils.date2Str(prod.getEnddate()));
        }
        if (prod.getLiquidtype() != null) {
            liquidType.setSelectValue(prod.getLiquidtype().toString());
        }
        if (prod.getPercent() != null) {
            percent.setText(prod.getPercent().toString());
        }
        dosageMessage.setText(prod.getDosagemessage());
        applicableObject.setText(prod.getApplicableobject());
        protectObject.setText(prod.getProtectobject());
        if (prod.getUsemethod() != null) {
            useMethod.setSelectValue(prod.getUsemethod().toString());
        }
        remark.setText(prod.getRemark());

    }
}
