/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalProductDetail.java
 *
 * Created on 2017-10-7, 14:24:37
 */
package QRCode.product;

import QRCode.base.Constants;
import QRCode.base.DataBaseUtil;
import QRCode.base.DateUtils;
import QRCode.base.StringUtils;
import QRCode.compnents.BaseDetailPanel;
import QRCode.compnents.MessageUtils;
import QRCode.product.model.Stock;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class PalStockDetail extends BaseDetailPanel {

    /** Creates new form PalProductDetail */
    public PalStockDetail(String operationType) {
        initComponents();
        initData();
        setOperationType(operationType);
    }

    /** Creates new form PalProductDetail */
    public PalStockDetail(String operationType, Integer id) {
        initComponents();
        this.id = id;
        setOperationType(operationType);
        initData();
    }

    /** Creates new form PalProductDetail */
    public PalStockDetail(JFrame pfa, JPanel parentJpanel, String operationType) {
        initComponents();
        setParentJframe(pfa);
        setParentJpanel(parentJpanel);
        setOperationType(operationType);
        initData();
    }

    private void initData() {

        startDate.setSelectDate(new Date());

        if (Constants.OPER_EDIT.equals(operationType)) {
            setModel(id);
            txtProdCode.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilCalendarModel1 = new net.sourceforge.jdatepicker.impl.UtilCalendarModel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        txtProdCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remark = new javax.swing.JTextArea();
        startDate = new QRCode.compnents.MyDatePicker();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStockName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtInPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSalePrice = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        type1 = new QRCode.compnents.MyCombobox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        type2 = new QRCode.compnents.MyCombobox();
        txtEffdays = new javax.swing.JTextField();

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel1.setText("商品别名：");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel2.setText("产品条码号：");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel3.setText("生产日期:");
        jLabel3.setName("jLabel3"); // NOI18N

        txtName2.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtName2.setName("txtName2"); // NOI18N

        txtProdCode.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtProdCode.setName("txtProdCode"); // NOI18N
        txtProdCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdCodeKeyReleased(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        remark.setColumns(20);
        remark.setFont(new java.awt.Font("Monospaced", 0, 18));
        remark.setRows(5);
        remark.setBorder(javax.swing.BorderFactory.createTitledBorder("备注"));
        remark.setName("remark"); // NOI18N
        jScrollPane1.setViewportView(remark);

        startDate.setName("startDate"); // NOI18N

        jLabel16.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel16.setText("生产公司:");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel17.setText("有效日期(日)：");
        jLabel17.setName("jLabel17"); // NOI18N

        txtCompany.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtCompany.setName("txtCompany"); // NOI18N

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel4.setText("商品名称：");
        jLabel4.setName("jLabel4"); // NOI18N

        txtStockName.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtStockName.setName("txtStockName"); // NOI18N
        txtStockName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel5.setText("进价：");
        jLabel5.setName("jLabel5"); // NOI18N

        txtInPrice.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtInPrice.setName("txtInPrice"); // NOI18N

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel6.setText("售价：");
        jLabel6.setName("jLabel6"); // NOI18N

        txtSalePrice.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtSalePrice.setName("txtSalePrice"); // NOI18N

        btnCancel.setText("取消");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("保存");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        type1.setName("type1"); // NOI18N

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel7.setText("二级类型：");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel8.setText("一级类型：");
        jLabel8.setName("jLabel8"); // NOI18N

        type2.setName("type2"); // NOI18N

        txtEffdays.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtEffdays.setName("txtEffdays"); // NOI18N
        txtEffdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEffdaysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEffdays, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(txtInPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtName2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtProdCode, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3))
                            .addComponent(jLabel16))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtStockName, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(startDate, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtSalePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(type2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtProdCode, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txtName2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEffdays, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtInPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(type2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, startDate, txtName2, txtProdCode});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnSave});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    Stock stock = getModel();
    Stock stock2 = DataBaseUtil.findStockByBarCode(stock.getBarcode());
    if (stock2 != null) {
        MessageUtils.showErrorMessage("该码在数据库中已存在，不再录入！", this);
        return;
    }
    int i = 0;
    if (Constants.OPER_ADD.equals(operationType)) {
        i = DataBaseUtil.saveStock(stock);
    } else {
        i = DataBaseUtil.updateStock(stock);
    }

    if (i > 0) {
        JOptionPane.showMessageDialog(this, "保存成功！");
        parentJframe.dispose();

    } else {
        JOptionPane.showMessageDialog(this, "保存失败！");
    }
}//GEN-LAST:event_btnSaveActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    parentJframe.dispose();
}//GEN-LAST:event_btnCancelActionPerformed

private void txtStockNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtStockNameActionPerformed

private void txtEffdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEffdaysActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtEffdaysActionPerformed

private void txtProdCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdCodeKeyReleased
    if (10 == evt.getKeyCode()) {
        Stock stock = DataBaseUtil.findStockByBarCode(txtProdCode.getText());
        if (stock != null) {
            MessageUtils.showErrorMessage("该码在数据库中已存在，不再录入！", this);
        }
    }
}//GEN-LAST:event_txtProdCodeKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea remark;
    private QRCode.compnents.MyDatePicker startDate;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtEffdays;
    private javax.swing.JTextField txtInPrice;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtProdCode;
    private javax.swing.JTextField txtSalePrice;
    private javax.swing.JTextField txtStockName;
    private QRCode.compnents.MyCombobox type1;
    private QRCode.compnents.MyCombobox type2;
    private net.sourceforge.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    // End of variables declaration//GEN-END:variables

    private Stock getModel() {
        Stock stock = new Stock();
        if (id != null) {
            stock.setId(id);
        } else {
            stock.setCreateTime(new Date());
        }
        stock.setBarcode(txtProdCode.getText());
        stock.setName(txtStockName.getText());
        stock.setName2(txtName2.getText());
        stock.setCompany(Integer.valueOf(txtCompany.getText()));
        stock.setEffdays(Integer.valueOf(txtEffdays.getText()));
        stock.setProduceDate(startDate.getSelectDate());
        stock.setInPrice(new BigDecimal(txtInPrice.getText()));
        stock.setSalePrice(new BigDecimal(txtSalePrice.getText()));
        stock.setCreateTime(new Date());
        if (!StringUtils.isNullOrEmpty(type1.getSelectValue())) {
            stock.setType1(Integer.valueOf(type1.getSelectValue()));
        }
        if (!StringUtils.isNullOrEmpty(type1.getSelectValue())) {
            stock.setType2(Integer.valueOf(type2.getSelectValue()));
        }
        stock.setRemark(remark.getText());
        stock.setRemainshare(1l);
        return stock;
    }

    public void setModel(Integer id) {
        this.id = id;
        Stock stock = DataBaseUtil.findStockByid(id);
        txtName2.setText(stock.getName());
        txtProdCode.setText(stock.getBarcode());
        txtCompany.setText(stock.getCompany().toString());
        if (stock.getProduceDate() != null) {
            startDate.setText(DateUtils.date2Str(stock.getProduceDate()));
        }
        remark.setText(stock.getRemark());

    }
}
