/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalStockuctManage.java
 *
 * Created on 2017-10-7, 9:47:00
 */
package QRCode.product;

import QRCode.MainPage;
import QRCode.base.Constants;
import QRCode.base.DataBaseUtil;
import QRCode.base.DateUtils;
import QRCode.product.model.Stock;
import QRCode.product.model.StockExample;
import QRCode.scanManage.PalBarcodeScan;
import com.mysql.jdbc.StringUtils;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *产品管理
 * @author Administrator
 */
public class PalStockManage extends javax.swing.JPanel {
    
    private int id;

    /** Creates new form PalStockuctManage */
    public PalStockManage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStockName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStockCode = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("货物管理"));

        jPanel1.setName("jPanel1"); // NOI18N

        btnSearch.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnSearch.setText("查询");
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnAdd.setText("新增");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnDel.setText("删除");
        btnDel.setName("btnDel"); // NOI18N
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnModify.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnModify.setText("修改");
        btnModify.setName("btnModify"); // NOI18N
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel1.setText("产品名称");
        jLabel1.setName("jLabel1"); // NOI18N

        txtStockName.setName("txtStockName"); // NOI18N
        txtStockName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockNameKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel2.setText("产品代码");
        jLabel2.setName("jLabel2"); // NOI18N

        txtStockCode.setName("txtStockCode"); // NOI18N

        btnSearch1.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnSearch1.setText("快速入库");
        btnSearch1.setName("btnSearch1"); // NOI18N
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStockCode, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch1)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDel, btnModify});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtStockCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnDel, btnModify, btnSearch});

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "选择", "货物编号", "名称", "别名", "生产厂家", "生产日期", "库存量", "进价", "售价"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    queryData();
}//GEN-LAST:event_btnSearchActionPerformed
    
private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    PalStockDetail detail = new PalStockDetail(Constants.OPER_ADD);
    JFrame jf = new JFrame();
    detail.setParentJframe(jf);
    detail.setParentJpanel(this);
    MainPage.showPanel(jf, detail, "新增产品");
}//GEN-LAST:event_btnAddActionPerformed
    
private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
    Integer id = null;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        if ((Boolean) jTable1.getValueAt(i, 1)) {
            id = new Integer(jTable1.getValueAt(i, 0).toString());
        }
    }
    if (id == null) {
        JOptionPane.showMessageDialog(this, "请选择一条记录");
        return;
    }
    PalStockDetail detail = new PalStockDetail(Constants.OPER_EDIT, id);
    JFrame jf = new JFrame();
    detail.setParentJframe(jf);
    detail.setParentJpanel(this);
    MainPage.showPanel(jf, detail, "修改产品");
}//GEN-LAST:event_btnModifyActionPerformed
    
private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
    Integer id = null;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        if ((Boolean) jTable1.getValueAt(i, 1)) {
            id = new Integer(jTable1.getValueAt(i, 0).toString());
        }
    }
    if (id == null) {
        JOptionPane.showMessageDialog(this, "请选择一条记录");
        return;
    }
    delStock(id);
}//GEN-LAST:event_btnDelActionPerformed
    
private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
    PalBarcodeScan detail = new PalBarcodeScan();
    JFrame jf = new JFrame();
    jf.setSize(detail.getPreferredSize());
    MainPage.showPanel(jf, detail, "新增商品");
}//GEN-LAST:event_btnSearch1ActionPerformed

private void txtStockNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockNameKeyReleased
    if (10 == evt.getKeyCode()) {
        queryData();
    }
}//GEN-LAST:event_txtStockNameKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtStockCode;
    private javax.swing.JTextField txtStockName;
    // End of variables declaration//GEN-END:variables

    public void queryData() {
        
        for (int i = jTable1.getModel().getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) jTable1.getModel()).removeRow(i);
        }
        StockExample prod = initQueryParam();
        List<Stock> l = DataBaseUtil.queryStockByModel(prod);
        if (l != null && !l.isEmpty()) {
            for (Stock p : l) {
                Object[] o = new Object[]{
                    p.getId(),
                    false,
                    p.getBarcode(),
                    p.getName(),
                    p.getName2(),
                    p.getCompany(),
                    p.getProduceDate() == null ? null : DateUtils.date2Str(p.getProduceDate()),
                    p.getRemainshare(),
                    p.getInPrice(),
                    p.getSalePrice()
                };
                ((DefaultTableModel) jTable1.getModel()).addRow(o);
            }
        } else {
            JOptionPane.showMessageDialog(this, "未查到数据！");
        }
    }
    
    private StockExample initQueryParam() {
        StockExample prod = new StockExample();
        if (!StringUtils.isNullOrEmpty(txtStockName.getText())) {
            prod.or().andName2Like(txtStockName.getText());
                    prod.or().andNameLike(txtStockName.getText());
        }
        if (!StringUtils.isNullOrEmpty(txtStockCode.getText())) {
            prod.createCriteria().andBarcodeEqualTo(txtStockCode.getText());
        }
        return prod;
    }
    
    private void delStock(Integer id) {
        int k = JOptionPane.showConfirmDialog(this, "是否确认删除?", "确认删除", JOptionPane.YES_NO_OPTION);
        //确认删除
        if (k != 0) {
            return;
        }
        int i = DataBaseUtil.delStock(id);
        if (i > 0) {
            JOptionPane.showMessageDialog(this, "删除成功！");
            queryData();
        } else {
            JOptionPane.showMessageDialog(this, "删除失败！");
        }
    }
}
