/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalProductManage.java
 *
 * Created on 2017-10-7, 9:47:00
 */
package QRCode.task;

import QRCode.MainPage;
import QRCode.base.Constants;
import QRCode.base.DataBaseUtil;
import QRCode.base.DateUtils;
import QRCode.base.StringUtils;
import QRCode.task.model.Task;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *任务管理
 * @author Administrator
 */
public class PalTaskManage extends javax.swing.JPanel {

    /** Creates new form PalProductManage */
    public PalTaskManage() {
        initComponents();
        prodid.setModel(DataBaseUtil.queryProdForCombo());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prodid = new QRCode.compnents.MyCombobox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setName("jPanel1"); // NOI18N

        btnSearch.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnSearch.setText("查询");
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnAdd.setText("新增任务");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnDel.setText("删除任务");
        btnDel.setName("btnDel"); // NOI18N
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnModify.setFont(new java.awt.Font("微软雅黑", 0, 14));
        btnModify.setText("修改任务");
        btnModify.setName("btnModify"); // NOI18N
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel1.setText("任务编号");
        jLabel1.setName("jLabel1"); // NOI18N

        txtProdName.setName("txtProdName"); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel2.setText("产品名称");
        jLabel2.setName("jLabel2"); // NOI18N

        prodid.setName("prodid"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(prodid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addGap(13, 13, 13)
                .addComponent(btnModify)
                .addGap(18, 18, 18)
                .addComponent(btnDel)
                .addGap(50, 50, 50))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDel, btnModify, btnSearch});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(prodid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnDel, btnModify, btnSearch});

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "选择", "任务编号", "产品名称", "生产批次", "生产线", "生产时间", "结束时间"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    queryData();
}//GEN-LAST:event_btnSearchActionPerformed

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    PalTaskDetail detail = new PalTaskDetail(Constants.OPER_ADD);
    JFrame jf = new JFrame();
    detail.setParentJframe(jf);
    detail.setParentJpanel(this);
    MainPage.showPanel(jf, detail, "新增任务");
}//GEN-LAST:event_btnAddActionPerformed

private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
    Integer id = null;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        if ((Boolean) jTable1.getValueAt(i, 1)) {
            id = new Integer(jTable1.getValueAt(i, 0).toString());
        }
    }
    if (id == null) {
        JOptionPane.showMessageDialog(this, "请选择一条记录");
          return;
    }
    PalTaskDetail detail = new PalTaskDetail(Constants.OPER_EDIT, id);
    JFrame jf = new JFrame();
    detail.setParentJframe(jf);
    detail.setParentJpanel(this);
    MainPage.showPanel(jf, detail, "修改任务");
}//GEN-LAST:event_btnModifyActionPerformed

private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
    Integer id = null;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        if ((Boolean) jTable1.getValueAt(i, 1)) {
            id = new Integer(jTable1.getValueAt(i, 0).toString());
        }
    }
    if (id == null) {
        JOptionPane.showMessageDialog(this, "请选择一条记录");
        return;
    }
    delTask(id);
}//GEN-LAST:event_btnDelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private QRCode.compnents.MyCombobox prodid;
    private javax.swing.JTextField txtProdName;
    // End of variables declaration//GEN-END:variables

    public void queryData() {

        for (int i = jTable1.getModel().getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) jTable1.getModel()).removeRow(i);
        }
        Task prod = initQueryParam();
        List<Task> l = DataBaseUtil.queryTaskByModel(prod);
        if (l != null && !l.isEmpty()) {
            for (Task p : l) {
                Object[] o = new Object[]{
                    p.getId(),
                    false,
                    p.getTaskcode(),
                    p.getProdName(),
                    p.getBatchnumber(),
                    p.getBatchline(),    
                    p.getBatchdate() == null ? null : DateUtils.date2Str(p.getBatchdate()),
                    p.getEnddate() == null ? null : DateUtils.date2Str(p.getEnddate())
                };
                ((DefaultTableModel) jTable1.getModel()).addRow(o);
            }
        } else {
            JOptionPane.showMessageDialog(this, "未查到数据！");
        }
    }

    private Task initQueryParam() {
        Task task = new Task();
        if (!StringUtils.isNullOrEmpty(prodid.getSelectedItem())) {
            task.setProdid(new Integer(prodid.getSelectValue()));
        }
        return task;
    }

    private void delTask(Integer id) {
        int k = JOptionPane.showConfirmDialog(this, "是否确认删除?", "确认删除", JOptionPane.YES_NO_OPTION);
        //确认删除
        if (k != 0) {
            return;
        }
        int i = DataBaseUtil.delTask(id);
        if (i > 0) {
            JOptionPane.showMessageDialog(this, "删除成功！");
            queryData();
        } else {
            JOptionPane.showMessageDialog(this, "删除失败！");
        }
    }
}
