/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalProductDetail.java
 *
 * Created on 2017-10-7, 14:24:37
 */
package QRCode.task;

import QRCode.base.Constants;
import QRCode.base.DataBaseUtil;
import QRCode.base.DateUtils;
import QRCode.base.StringUtils;
import QRCode.compnents.BaseDetailPanel;
import QRCode.task.model.Task;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class PalTaskDetail extends BaseDetailPanel {

    /** Creates new form PalProductDetail */
    public PalTaskDetail(String operationType) {
        initComponents();
        initData();
       setOperationType(operationType);
    }

    /** Creates new form PalProductDetail */
    public PalTaskDetail(String operationType, Integer id) {
        initComponents();
        this.id = id;
        setOperationType(operationType);
        initData();
    }

    /** Creates new form PalProductDetail */
    public PalTaskDetail(JFrame pfa, JPanel parentJpanel, String operationType) {
        initComponents();
        setParentJframe(pfa);
        setParentJpanel(parentJpanel);
        setOperationType(operationType);
        initData();
    }

    private void initData() {
        prodid.setModel(DataBaseUtil.queryProdForCombo());
        batchDate.setSelectDate(new Date());
        endDate.setSelectDate(new Date());
        if (Constants.OPER_EDIT.equals(operationType)) {
            setModel(id);
            txtTaskCode.setEnabled(false);
            batchDate.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilCalendarModel1 = new net.sourceforge.jdatepicker.impl.UtilCalendarModel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTaskCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remark = new javax.swing.JTextArea();
        batchDate = new QRCode.compnents.MyDatePicker();
        endDate = new QRCode.compnents.MyDatePicker();
        standard = new javax.swing.JTextField();
        prodid = new QRCode.compnents.MyCombobox();
        batchNumber = new javax.swing.JTextField();
        batchLine = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel1.setText("产品名称：");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel2.setText("任务编号：");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel3.setText("生产日期：");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel6.setText("生产批次：");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel7.setText("生产线");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel8.setText("规格：");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel10.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel10.setText("有效结束日期：");
        jLabel10.setName("jLabel10"); // NOI18N

        txtTaskCode.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtTaskCode.setName("txtTaskCode"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        remark.setColumns(20);
        remark.setRows(5);
        remark.setBorder(javax.swing.BorderFactory.createTitledBorder("备注"));
        remark.setName("remark"); // NOI18N
        jScrollPane1.setViewportView(remark);

        batchDate.setName("batchDate"); // NOI18N

        endDate.setName("endDate"); // NOI18N

        standard.setFont(new java.awt.Font("微软雅黑", 0, 14));
        standard.setName("standard"); // NOI18N

        prodid.setName("prodid"); // NOI18N

        batchNumber.setFont(new java.awt.Font("微软雅黑", 0, 14));
        batchNumber.setName("batchNumber"); // NOI18N

        batchLine.setFont(new java.awt.Font("微软雅黑", 0, 14));
        batchLine.setName("batchLine"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(standard)
                                .addComponent(txtTaskCode, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(batchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batchLine, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prodid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDate, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(batchDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(prodid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaskCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(batchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(batchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batchLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(standard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnSave.setText("保存");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnSave});

    }// </editor-fold>//GEN-END:initComponents

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    Task task = getModel();
    int i = 0;
    if (Constants.OPER_ADD.equals(operationType)) {
        i = DataBaseUtil.saveTask(task);
    } else {
        i = DataBaseUtil.updateTask(task);
    }

    if (i > 0) {
        JOptionPane.showMessageDialog(this, "保存成功！");
        parentJframe.dispose();
        ((PalTaskManage) parentJpanel).queryData();
    } else {
        JOptionPane.showMessageDialog(this, "保存失败！");
    }
}//GEN-LAST:event_btnSaveActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    parentJframe.dispose();
}//GEN-LAST:event_btnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QRCode.compnents.MyDatePicker batchDate;
    private javax.swing.JTextField batchLine;
    private javax.swing.JTextField batchNumber;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private QRCode.compnents.MyDatePicker endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private QRCode.compnents.MyCombobox prodid;
    private javax.swing.JTextArea remark;
    private javax.swing.JTextField standard;
    private javax.swing.JTextField txtTaskCode;
    private net.sourceforge.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    // End of variables declaration//GEN-END:variables

    private Task getModel() {
        Task task = new Task();
        if (id != null) {
            task.setId(id);
        }
        if (!StringUtils.isNullOrEmpty(txtTaskCode.getText())) {
            task.setTaskcode(txtTaskCode.getText());
        }
        if (!StringUtils.isNullOrEmpty(prodid.getSelectedItem())) {
            task.setProdid(new Integer(prodid.getSelectValue()));
        }
        if (!StringUtils.isNullOrEmpty(batchNumber.getText())) {
            task.setBatchnumber(batchNumber.getText());
        }
        task.setBatchline(batchLine.getText());
        if (!StringUtils.isNullOrEmpty(batchDate.getSelectedItem())) {
            task.setBatchdate(DateUtils.str2Date((String) batchDate.getSelectedItem()));
        }
        if (!StringUtils.isNullOrEmpty(endDate.getSelectedItem())) {
            task.setEnddate(DateUtils.str2Date((String) endDate.getSelectedItem()));
        }
        if (!StringUtils.isNullOrEmpty(standard.getText())) {
            task.setStandard(standard.getText());
        }
        task.setRemark(remark.getText());
        return task;
    }

    public void setModel(Integer id) {
        this.id = id;
        Task task = DataBaseUtil.findTaskByid(id);
        txtTaskCode.setText(task.getTaskcode());

        if (task.getProdid() != null) {
            prodid.setSelectValue(task.getProdid().toString());
        }
        if (task.getBatchnumber() != null) {
            batchNumber.setText(task.getBatchnumber());
        }
        if (task.getBatchline() != null) {
            batchLine.setText(task.getBatchline());
        }
        if (task.getBatchdate() != null) {
            batchDate.setText(DateUtils.date2Str(task.getBatchdate()));
        }
        if (task.getEnddate() != null) {
            endDate.setText(DateUtils.date2Str(task.getEnddate()));
        }
        if (task.getStandard() != null) {
            standard.setText(task.getStandard());
        }
        remark.setText(task.getRemark());

    }
}
