/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelInandOut.java
 *
 * Created on 2017-8-6, 17:24:57
 */
package spmkt.deal;

import com.mysql.jdbc.StringUtils;
import spmkt.base.DataBaseUtil;
import spmkt.deal.model.OrderModel;
import spmkt.deal.model.StockDealModel;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import spmkt.deal.model.Stock;

/**
 *
 * @author Administrator
 */
public class PanelCashDeal extends javax.swing.JPanel {

    private List<StockDealModel> stocks = new ArrayList<StockDealModel>();
    private OrderModel order = new OrderModel();

    /** Creates new form PanelInandOut */
    public PanelCashDeal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDealDetails = new javax.swing.JTextArea();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtInputText = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(444, 613));
        setMinimumSize(new java.awt.Dimension(444, 613));
        setName("Form"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(460, 613));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtDealDetails.setColumns(20);
        txtDealDetails.setEditable(false);
        txtDealDetails.setRows(5);
        txtDealDetails.setName("txtDealDetails"); // NOI18N
        jScrollPane1.setViewportView(txtDealDetails);

        txtTotalPrice.setEditable(false);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(PanelCashDeal.class);
        txtTotalPrice.setFont(resourceMap.getFont("txtTotalPrice.font")); // NOI18N
        txtTotalPrice.setText(resourceMap.getString("txtTotalPrice.text")); // NOI18N
        txtTotalPrice.setName("txtTotalPrice"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtInputText.setText(resourceMap.getString("txtInputText.text")); // NOI18N
        txtInputText.setName("txtInputText"); // NOI18N
        txtInputText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(txtInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(txtInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int k = JOptionPane.showConfirmDialog(this, "是否确认结账?", "确认结账", JOptionPane.YES_NO_OPTION);
    //确认结账
    if (k != 0) {
        return;
    }
    order.setStocks(stocks);
    int i = DataBaseUtil.inserDeal(order);
    if (i > 0) {
        JOptionPane.showMessageDialog(jButton1, "结账成功：共 " + order.getTotalPrice() + "元");
    } else {
        JOptionPane.showMessageDialog(jButton1, "结账失败");
    }
    stocks.clear();
    order = new OrderModel();
    txtInputText.requestFocus();
}//GEN-LAST:event_jButton1ActionPerformed

private void txtInputTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputTextKeyReleased
    String s = txtInputText.getText();
    //回车键
    if (evt.getKeyCode() == 10) {
        calTotalPrice(s);
        txtInputText.setText(null);
    }
    txtInputText.requestFocus();
}//GEN-LAST:event_txtInputTextKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDealDetails;
    private javax.swing.JTextField txtInputText;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    private void calTotalPrice(String text) {
        if (StringUtils.isNullOrEmpty(text)) {
            jButton1ActionPerformed(null);
            return;
        }
        StockDealModel deal = getDealModel(text);
        String details = txtDealDetails.getText();
        details = details + "\n" + deal.getStockName() + ":" + deal.getPrice();
        txtDealDetails.setText(details);
        String totalStr = txtTotalPrice.getText();
        BigDecimal totalPrice = BigDecimal.ZERO;
        if (StringUtils.isNullOrEmpty(totalStr)) {
            totalStr = "";
        } else {
            totalPrice = new BigDecimal(totalStr);
        }
        totalPrice = totalPrice.add(deal.getPrice());
        txtTotalPrice.setText(totalPrice.toString());

    }

    private StockDealModel getDealModel(String textCode) {
        Stock stock = DataBaseUtil.queryStockByBarcode(textCode);
        StockDealModel deal = new StockDealModel();
        deal.setDealdate(new Date());
        deal.setPrice(stock.getSellingprice());
        deal.setStockId(stock.getId());
        deal.setStockName(stock.getName());
        if (order.getStocks() == null) {
            stocks.add(deal);
            order.setTotalPrice(stock.getSellingprice());
        } else {
            stocks.add(deal);
            order.setTotalPrice(order.getTotalPrice().add(stock.getSellingprice()));
        }
        return deal;
    }
}
