/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalCompanyDetail.java
 *
 * Created on 2017-10-7, 14:24:37
 */
package QRCode.company;

import QRCode.base.Constants;
import QRCode.base.DataBaseUtil;
import QRCode.compnents.BaseDetailPanel;
import QRCode.company.model.Company;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class PalCompanyDetail extends BaseDetailPanel {

    /** Creates new form PalCompanyDetail */
    public PalCompanyDetail(String operationType) {
        initComponents();
        initData();
        setOperationType(operationType);
    }

    /** Creates new form PalCompanyDetail */
    public PalCompanyDetail(String operationType, Integer id) {
        initComponents();
        this.id = id;
        setOperationType(operationType);
        initData();
    }

    /** Creates new form PalCompanyDetail */
    public PalCompanyDetail(JFrame pfa, JPanel parentJpanel, String operationType) {
        initComponents();
        setParentJframe(pfa);
        setParentJpanel(parentJpanel);
        setOperationType(operationType);
        initData();
    }
    
    private void initData() {
        
        if (Constants.OPER_EDIT.equals(operationType)) {
            setModel(id);
            txtCompanyName.setEnabled(false);
            txtPhoneNum.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilCalendarModel1 = new net.sourceforge.jdatepicker.impl.UtilCalendarModel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFaxNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel1.setText("公司地址：");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel2.setText("公司名称：");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel4.setText("联系人电话号：");
        jLabel4.setName("jLabel4"); // NOI18N

        txtAddress.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtAddress.setName("txtAddress"); // NOI18N

        txtCompanyName.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtCompanyName.setName("txtCompanyName"); // NOI18N

        txtPhoneNum.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtPhoneNum.setName("txtPhoneNum"); // NOI18N

        jLabel15.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel15.setText("传真号码：");
        jLabel15.setName("jLabel15"); // NOI18N

        txtFaxNum.setFont(new java.awt.Font("微软雅黑", 0, 14));
        txtFaxNum.setName("txtFaxNum"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFaxNum)
                    .addComponent(txtPhoneNum)
                    .addComponent(txtAddress)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, txtAddress, txtCompanyName, txtFaxNum, txtPhoneNum});

        btnSave.setText("保存");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    Company company = getModel();
    int i = 0;
    if (Constants.OPER_ADD.equals(operationType)) {
        i = DataBaseUtil.saveCompany(company);
    } else {
        i = DataBaseUtil.updateCompany(company);
    }
    
    if (i > 0) {
        JOptionPane.showMessageDialog(this, "保存成功！");
        parentJframe.dispose();
        ((PalCompanyManage) parentJpanel).queryData();
    } else {
        JOptionPane.showMessageDialog(this, "保存失败！");
    }
}//GEN-LAST:event_btnSaveActionPerformed
    
private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    parentJframe.dispose();
}//GEN-LAST:event_btnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtPhoneNum;
    private net.sourceforge.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    // End of variables declaration//GEN-END:variables

    private Company getModel() {
        Company company = new Company();
        if (id != null) {
            company.setId(id);
        }        
        company.setAddress(txtAddress.getText());
        company.setName(txtCompanyName.getText());
        company.setPhonenumber(txtPhoneNum.getText());
        company.setFaxnumber(txtFaxNum.getText());
        return company;
    }
    
    public void setModel(Integer id) {
        this.id = id;
        Company company = DataBaseUtil.findCompanyByid(id);
        txtAddress.setText(company.getAddress());
        txtCompanyName.setText(company.getName());
        txtPhoneNum.setText(company.getPhonenumber());
        txtFaxNum.setText(company.getFaxnumber());
    }
}
