/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * stockManagePage.java
 *
 * Created on 2017-9-22, 19:51:18
 */
package QRCode.manage;

import QRCode.base.DataBaseUtil;
import QRCode.base.StringUtils;
import QRCode.product.model.Stock;
import QRCode.product.model.StockExample;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class PalQuickScan extends javax.swing.JPanel {

    /** Creates new form stockManagePage */
    public PalQuickScan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStockName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStockCode = new javax.swing.JTextField();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "货物名", "货物名2", "库存量", "售价", "barcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("查询");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("货物名称：");
        jLabel1.setName("jLabel1"); // NOI18N

        txtStockName.setName("txtStockName"); // NOI18N
        txtStockName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockNameKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("条形码/自定义码：");
        jLabel2.setName("jLabel2"); // NOI18N

        txtStockCode.setName("txtStockCode"); // NOI18N
        txtStockCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockCodeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStockCode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStockName, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStockCode, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    query();
}//GEN-LAST:event_jButton1ActionPerformed

private void txtStockNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockNameKeyReleased
    if (evt.getKeyCode() == 10) {
        query();
    }
}//GEN-LAST:event_txtStockNameKeyReleased

private void txtStockCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockCodeKeyReleased
    if (evt.getKeyCode() == 10) {
        query();
    }
}//GEN-LAST:event_txtStockCodeKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtStockCode;
    private javax.swing.JTextField txtStockName;
    // End of variables declaration//GEN-END:variables

    private void query() {
        for (int i = jTable1.getModel().getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) jTable1.getModel()).removeRow(i);
        }
        StockExample stockExample = initQueryParam();
        List<Stock> list = DataBaseUtil.queryStockByModel(stockExample);
        if (list != null && !list.isEmpty()) {
            for (int i = 0; i < list.size(); i++) {
                Stock stock = list.get(i);
                Object[] o = new Object[]{
                    stock.getName(),
                    stock.getName2(),
                    stock.getRemainshare(),
                    stock.getSalePrice(),
                    stock.getBarcode()
                };
                ((DefaultTableModel) jTable1.getModel()).addRow(o);
            }
        }
    }
    
    private StockExample initQueryParam() {
        StockExample prod = new StockExample();
        if (!StringUtils.isNullOrEmpty(txtStockName.getText())) {
            prod.or().andName2Like(txtStockName.getText());
                    prod.or().andNameLike(txtStockName.getText());
        }
        if (!StringUtils.isNullOrEmpty(txtStockCode.getText())) {
            prod.createCriteria().andBarcodeEqualTo(txtStockCode.getText());
        }
        return prod;
    }
}
