/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BaseDetailPanel.java
 *
 * Created on 2017-10-8, 15:08:40
 */
package QRCode.compnents;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class BaseDetailPanel extends javax.swing.JPanel {
    protected  JFrame parentJframe;
    protected  Integer id;
    protected JPanel parentJpanel;
    protected  String operationType;
    /** Creates new form BaseDetailPanel */
    public BaseDetailPanel() {
        initComponents();
    }

    public String getOperationType() {
        return operationType;
    }

    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public JFrame getParentJframe() {
        return parentJframe;
    }

    public void setParentJframe(JFrame parentJframe) {
        this.parentJframe = parentJframe;
    }

    public JPanel getParentJpanel() {
        return parentJpanel;
    }

    public void setParentJpanel(JPanel parentJpanel) {
        this.parentJpanel = parentJpanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
